### ISSUE TITLE
quick doubt

### ISSUE THREAD

**Issue by nostorian** [Iapetus-11/petu-api#2]
for the secrets, the url we enter, in the `url` place, should be our host's url which the api will access right? i will be using https://railway.app for hosting the api and they give subdomains like `yourprojectname-production.railway.app`
and for the database, are we supposed to only use postgresql for this api?

**Comment by Iapetus-11** [comment]
By url do you mean the Seq Url? And yeah it only supports PostgreSQL but it shouldn't be too hard to make it use another db.

**Comment by nostorian** [comment]
ye i mean seq url

**Comment by Iapetus-11** [comment]
This is Seq: https://datalust.co/seq

**Comment by nostorian** [comment]
is it mandatory i put the seq url? can i just skip it and add the database details?

**Comment by Iapetus-11** [comment]
I'm not sure
